### PR TITLE
fix: preserve truthy defaults when glob options are passed as undefined

### LINKED ISSUE #198: truthy defaults ignored when glob options are explicitly passed as `undefined`
### Description
Passing any option explicitly as `undefined` causes the corresponding default to be silently dropped, because the spread `{ ...defaultOptions, ...options }` lets explicit undefined values overwrite the truthy defaults.

Based on this comment (`src/index.ts:17`):
```ts
// Object containing all default options to ensure there is **no hidden state difference
// between false and undefined**.
const defaultOptions: GlobOptions = {
  caseSensitiveMatch: true,
  cwd: process.cwd(),
  debug: !!process.env.TINYGLOBBY_DEBUG,
  expandDirectories: true,
  followSymbolicLinks: true,
  onlyFiles: true
};
```

---

### Reproduction
```ts
import { glob } from 'tinyglobby';

// throws TypeError: path must be a string -- resolve(undefined)
await glob('*', { cwd: undefined });

// returns [] instead of matching files -- expandDirectories disabled
await glob('a', { cwd: '.', expandDirectories: undefined });

// returns dirs too -- onlyFiles disabled  
await glob('a', { cwd: '.', onlyFiles: undefined });

// matches case-insensitively -- caseSensitiveMatch disabled
await glob('**/A.TXT', { cwd: '.', caseSensitiveMatch: undefined });
```

---

### Comments
Seems to be introduced in #170, which inlined `normalizeCwd`, but introduced a behavioural change.

The old `normalizeCwd` had an explicit if `(!cwd) guard`, but the current spread does not skip `undefined` keys, so any option passed as `undefined` explicitly now overwrites the default.

### PR DESCRIPTION
**Pull request by chloeelim**
### Description

Fixes a regression introduced in #170 where spreading user-supplied glob options over `defaultOptions` allowed explicit `undefined` values to overwrite the truthy defaults.

The old `normalizeCwd` function guarded against the undefined `cwd` explicitly, but the refactor lost that guard.

This PR introduces a fix to `getOptions` which now iterates over the fixed set of `defaultOptions` keys, filling in any user-supplied option that is `undefined`.

Closes https://github.com/SuperchupuDev/tinyglobby/issues/198

---

### Tests

Added tests verifying that the glob options all apply their truthy defaults when passed explicitly as undefined.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -15,20 +15,27 @@ function formatPaths(paths: string[], mapper?: false | RelativeMapper) {
...
 function getOptions(options?: GlobOptions): InternalOptions {
-  const opts = { ...defaultOptions, ...options } as InternalOptions;
+  const opts = Object.assign({}, options) as InternalOptions;
+  for (const key in defaultOptions) {
+    if (opts[key as keyof GlobOptions] === undefined) {
+      Object.assign(opts, { [key]: defaultOptions[key as keyof GlobOptions] });
+    }
+  }
+
+  const resolvedCwd = opts.cwd instanceof URL ? fileURLToPath(opts.cwd) : resolve(opts.cwd ?? process.cwd());
```
Comment (SuperchupuDev) [inline src/index.ts]: nit: as much as i love using `??` instead of `||` everywhere i can, sadly `tsdown` downlevels it for compat purposes which increases the bundle size. so we might be better off using `||`

```suggestion
  const resolvedCwd = opts.cwd instanceof URL ? fileURLToPath(opts.cwd) : resolve(opts.cwd || process.cwd());
```

File: test/index.test.ts [hunk 2]
```diff
@@ -299,6 +299,39 @@ test('absolute + empty commonPath', async () => {
...
 
+test('common path prefix is respected across multiple patterns', async () => {
+  const files = await glob(['a/a.txt', 'a/b.txt'], { cwd });
+  assert.deepEqual(files.sort(), ['a/a.txt', 'a/b.txt']);
+});
+
+test('cwd defaults to process.cwd() evaluated at call time, not import time', async () => {
+  const importTimeCwd = process.cwd();
+  try {
+    process.chdir(cwd); // cwd !== importTimeCwd (fixture is in a temp dir)
```
Comment (SuperchupuDev) [inline test/index.test.ts]: i am slightly afraid that changing the current directory might mess with tests, but it looks like tests are passing, so it's probably not a big deal

**Review by SuperchupuDev — APPROVED** [review]
thanks a lot for fixing this regression ❤️ i have two small nits but other than that it looks good to me!!

File: test/index.test.ts (hunk 2 above)
Comment (chloeelim) [reply test/index.test.ts]: good point! mocked it instead in [fix(test): mock process.cwd() method in cwd test](https://github.com/SuperchupuDev/tinyglobby/pull/199/commits/fe88eb9f5a11b0602732e985eff9a04a19447cd3)! wonder if that's better?

File: test/index.test.ts [hunk 3]
```diff
@@ -299,6 +299,34 @@ test('absolute + empty commonPath', async () => {
...
 
+test('common path prefix is respected across multiple patterns', async () => {
+  const files = await glob(['a/a.txt', 'a/b.txt'], { cwd });
+  assert.deepEqual(files.sort(), ['a/a.txt', 'a/b.txt']);
+});
+
+test('cwd defaults to process.cwd() evaluated at call time, not import time', async t => {
+  t.mock.method(process, 'cwd', () => cwd); // cwd !== importTimeCwd (fixture is in a temp dir)
+  const files = await glob('a/*.txt'); // no cwd passed - must use call-time process.cwd()
+  assert.deepEqual(files.sort(), ['a/a.txt', 'a/b.txt']);
```
Comment (SuperchupuDev) [inline test/index.test.ts]: small thing i missed: you forgot to restore the mock after the test. see the test at line 157 for an example of how it's done. will merge after that :^)

Comment (chloeelim) [reply test/index.test.ts]: fixed this in [fix(test): explicitly restore mock after use](https://github.com/SuperchupuDev/tinyglobby/pull/199/commits/dcd9da907e55dd34f0c72f8018dc17c4c41e21fe)!

but i think mocking via the test context will automatically restore the mocks though (ref: https://nodejs.org/api/test.html#mocking) (cmiiw), changed it still as explicitly restoring the mock for readability + consistency~

thanks for the thorough review!! (ps tinyglobby is such a cute name) :))

Comment (SuperchupuDev) [reply test/index.test.ts]: thank you!! had no idea mocks were automatically restored that way, will update the tests to not manually restore them anymore

**Review by SuperchupuDev — APPROVED** [review]
thank you for reporting the bug and for submitting a fix so quickly, this would've taken a lot longer without your help ❤️

**Comment by kevinmarrec** [comment]
@SuperchupuDev Any idea when 0.2.17 is landing ? :)

**Comment by SuperchupuDev** [comment]
i was gonna wait some days to see if i can close more issues before releasing but i can hurry up if anyone needs the release :^) i can try doing the release this week

**Comment by kevinmarrec** [comment]
No real rush for me, I just made my Renovate/Dependabot settings to stop bumping `tinyglobby` (even pinned) for now, I can wait :)

**Comment by SuperchupuDev** [comment]
hi! just fyi [0.2.17](https://github.com/SuperchupuDev/tinyglobby/releases/tag/0.2.17) is out now with the fix :^) @kevinmarrec

**Comment by kevinmarrec** [comment]
Great 🎉
